url: "https://yhuang94.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Yang Huang" # the name of your site, e.g. ACME Corp.
description: "Postdoctoral Researcher | CFD | FSI | Ocean Renewable Energy"
